# Generated by Django 3.2.7 on 2022-06-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220613_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='save',
            new_name='show',
        ),
    ]
