# Generated by Django 3.2.7 on 2022-06-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220606_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Tienda: Producto', 'verbose_name_plural': 'Tienda: Productos'},
        ),
    ]
