# Generated by Django 3.2.7 on 2022-06-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='outstanding',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', '1-3 Años'), ('B', 'Bebés'), ('C', '3 Años en Adelante'), ('D', 'Otros')], max_length=2),
        ),
    ]
