# Generated by Django 3.2.7 on 2022-06-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220611_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='save',
            new_name='show',
        ),
    ]
